apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-test-app
  namespace: autoscale-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaling-test-app
  template:
    metadata:
      labels:
        app: scaling-test-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 900m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi
      nodeSelector:
        gke-pool-type: autoscale-test
      tolerations:
      - effect: NoSchedule
        key: autoscale-test
        operator: Equal
        value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: scaling-test-app
  namespace: autoscale-test
spec:
  selector:
    app: scaling-test-app
  ports:
  - port: 80
    targetPort: 80
